// bootstrap: sets up the Arch Linux ARM rootfs on first install.
// I download the Arch ARM bootstrap tarball, extract it to
// PHANTOM_ROOT, rank mirrors by latency, init the pacman keyring,
// then hand off to pacman for the rest.
//
// Why not Termux? Termux patches packages and lags behind upstream.
// I want real Arch packages, bleeding edge, zero modifications.
// The trick is running everything inside a chroot so Arch's paths
// (/usr, /lib, /etc) stay intact — no prefix hacks needed.
package main

import (
	"archive/tar"
	"compress/gzip"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"io"
	"net/http"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"sort"
	"strings"
	"time"
)

const (
	// I keep my entire environment here — separate from Android system
	PHANTOM_ROOT = "/data/phantom/rootfs"
	PHANTOM_BIN  = "/data/phantom/bin"

	// Arch Linux ARM bootstrap tarballs
	BOOTSTRAP_URL_64 = "https://mirror.archlinuxarm.org/aarch64/core/pacman-6.0.2-7-aarch64.pkg.tar.xz"
	ALARM_MIRROR     = "https://mirror.archlinuxarm.org"

	// I use this repo path inside the rootfs
	PACMAN_CONF = PHANTOM_ROOT + "/etc/pacman.conf"
)

// Mirror holds a mirror URL and its measured latency
type Mirror struct {
	URL     string
	Latency time.Duration
}

// rankMirrors pings each Arch ARM mirror and returns them sorted fastest first.
// I do this once at setup so pacman is always pulling from the closest server.
func rankMirrors() []Mirror {
	candidates := []string{
		"https://mirror.archlinuxarm.org",
		"https://mirrors.edge.kernel.org/archlinuxarm",
		"https://de3.mirror.archlinuxarm.org",
		"https://sg.mirror.archlinuxarm.org",
		"https://au.mirror.archlinuxarm.org",
		"https://mirror2.totaal-dns.nl/archlinuxarm",
	}

	results := make([]Mirror, 0, len(candidates))
	for _, url := range candidates {
		start := time.Now()
		resp, err := http.Head(url + "/$arch/$repo/os/$arch")
		if err != nil || resp.StatusCode >= 400 {
			continue
		}
		results = append(results, Mirror{URL: url, Latency: time.Since(start)})
	}
	sort.Slice(results, func(i, j int) bool {
		return results[i].Latency < results[j].Latency
	})
	return results
}

// writePacmanConf writes /etc/pacman.conf with ranked mirrors.
// I write the top 3 fastest mirrors as Server lines so pacman
// automatically falls back if one is slow.
func writePacmanConf(mirrors []Mirror) error {
	var sb strings.Builder
	sb.WriteString("# Generated by phantom-bootstrap — do not edit manually\n")
	sb.WriteString("[options]\n")
	sb.WriteString("HoldPkg     = pacman glibc\n")
	sb.WriteString("Architecture = ")
	if runtime.GOARCH == "arm64" {
		sb.WriteString("aarch64\n")
	} else {
		sb.WriteString("armv7h\n")
	}
	sb.WriteString("CheckSpace\n")
	sb.WriteString("ParallelDownloads = 5\n\n")

	repos := []string{"core", "extra", "community", "alarm", "aur"}
	for _, repo := range repos {
		sb.WriteString(fmt.Sprintf("[%s]\n", repo))
		top := 3
		if len(mirrors) < top {
			top = len(mirrors)
		}
		for _, m := range mirrors[:top] {
			sb.WriteString(fmt.Sprintf("Server = %s/$arch/%s/os/$arch\n", m.URL, repo))
		}
		sb.WriteString("\n")
	}

	return os.WriteFile(PACMAN_CONF, []byte(sb.String()), 0644)
}

// downloadAndVerify downloads url, checks sha256, returns the file path.
func downloadAndVerify(url, expectedHash string) (string, error) {
	resp, err := http.Get(url)
	if err != nil {
		return "", fmt.Errorf("download failed: %w", err)
	}
	defer resp.Body.Close()

	tmp, err := os.CreateTemp("", "phantom-bootstrap-*")
	if err != nil {
		return "", err
	}
	defer tmp.Close()

	h := sha256.New()
	if _, err := io.Copy(io.MultiWriter(tmp, h), resp.Body); err != nil {
		return "", err
	}
	if expectedHash != "" {
		got := hex.EncodeToString(h.Sum(nil))
		if got != expectedHash {
			os.Remove(tmp.Name())
			return "", fmt.Errorf("checksum mismatch: got %s want %s", got, expectedHash)
		}
	}
	return tmp.Name(), nil
}

// extractTarGz extracts a .tar.gz into destDir, preserving ownership.
func extractTarGz(path, destDir string) error {
	f, err := os.Open(path)
	if err != nil {
		return err
	}
	defer f.Close()

	gz, err := gzip.NewReader(f)
	if err != nil {
		return err
	}
	defer gz.Close()

	tr := tar.NewReader(gz)
	for {
		hdr, err := tr.Next()
		if err == io.EOF {
			break
		}
		if err != nil {
			return err
		}
		target := filepath.Join(destDir, hdr.Name)
		switch hdr.Typeflag {
		case tar.TypeDir:
			os.MkdirAll(target, os.FileMode(hdr.Mode))
		case tar.TypeReg:
			os.MkdirAll(filepath.Dir(target), 0755)
			out, err := os.OpenFile(target, os.O_CREATE|os.O_WRONLY|os.O_TRUNC, os.FileMode(hdr.Mode))
			if err != nil {
				return err
			}
			io.Copy(out, tr)
			out.Close()
		case tar.TypeSymlink:
			os.Symlink(hdr.Linkname, target)
		}
	}
	return nil
}

// chrootExec runs a command inside the Arch rootfs.
// I bind-mount /proc /sys /dev from Android so tools that need them work.
func chrootExec(args ...string) error {
	// bind mounts needed inside the rootfs
	for _, mp := range []string{"/proc", "/sys", "/dev"} {
		exec.Command("mount", "--bind", mp, PHANTOM_ROOT+mp).Run()
	}
	cmd := exec.Command("chroot", append([]string{PHANTOM_ROOT}, args...)...)
	cmd.Stdin  = os.Stdin
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	return cmd.Run()
}

func main() {
	fmt.Println("phantom bootstrap — setting up Arch Linux ARM environment")

	// 1. create rootfs directory
	if err := os.MkdirAll(PHANTOM_ROOT, 0755); err != nil {
		fmt.Fprintf(os.Stderr, "failed to create rootfs: %v\n", err)
		os.Exit(1)
	}

	// 2. rank mirrors — find fastest Arch ARM mirror for my region
	fmt.Print("ranking mirrors... ")
	mirrors := rankMirrors()
	if len(mirrors) == 0 {
		fmt.Fprintln(os.Stderr, "no reachable mirrors found")
		os.Exit(1)
	}
	fmt.Printf("fastest: %s (%dms)\n", mirrors[0].URL, mirrors[0].Latency.Milliseconds())

	// 3. download Arch ARM bootstrap tarball from fastest mirror
	arch := "aarch64"
	if runtime.GOARCH == "arm" {
		arch = "armv7h"
	}
	bootstrapURL := fmt.Sprintf("%s/%s/iso/latest/archlinuxarm-%s-latest.tar.gz",
		mirrors[0].URL, arch, arch)

	fmt.Printf("downloading bootstrap from %s\n", bootstrapURL)
	tarPath, err := downloadAndVerify(bootstrapURL, "")
	if err != nil {
		fmt.Fprintf(os.Stderr, "download failed: %v\n", err)
		os.Exit(1)
	}
	defer os.Remove(tarPath)

	// 4. extract into rootfs
	fmt.Print("extracting rootfs... ")
	if err := extractTarGz(tarPath, PHANTOM_ROOT); err != nil {
		fmt.Fprintf(os.Stderr, "extract failed: %v\n", err)
		os.Exit(1)
	}
	fmt.Println("done")

	// 5. write pacman.conf with ranked mirrors
	if err := writePacmanConf(mirrors); err != nil {
		fmt.Fprintf(os.Stderr, "failed to write pacman.conf: %v\n", err)
		os.Exit(1)
	}

	// 6. init pacman keyring inside rootfs
	fmt.Println("initializing pacman keyring...")
	chrootExec("pacman-key", "--init")
	chrootExec("pacman-key", "--populate", "archlinuxarm")

	// 7. full system sync
	fmt.Println("syncing package databases...")
	chrootExec("pacman", "-Syu", "--noconfirm")

	// 8. install yay or paru depending on user preference
	// default: yay (Go binary, I can cross-compile it myself)
	fmt.Println("installing yay (AUR helper)...")
	chrootExec("pacman", "-S", "--noconfirm", "yay")

	// 9. symlink psh into rootfs so it's available inside the chroot too
	os.Symlink(PHANTOM_BIN+"/psh", PHANTOM_ROOT+"/usr/bin/psh")
	os.Symlink(PHANTOM_BIN+"/ph",  PHANTOM_ROOT+"/usr/bin/ph")

	fmt.Println("\nphantom environment ready.")
	fmt.Println("use 'psh' to enter the shell or 'psh -S <pkg>' to install packages")
}
