// phantom-bundler — bundles a Phantom JS script and its @import dependencies
// into a single self-contained .js file ready for deployment.
//
// Usage:
//   phantom-bundler <input.js> [-o output.js]
//
// @import syntax (top of file):
//   // @import ./utils/helpers.js
//   // @import ./lib/crypto.js
//
// Imports are resolved relative to the input file and inlined.
// Circular imports are detected and skipped.
// The @layer directive is preserved at the top of the bundle.

package main

import (
	"bufio"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

type bundler struct {
	seen map[string]bool
	out  strings.Builder
}

func (b *bundler) bundle(path string) error {
	abs, err := filepath.Abs(path)
	if err != nil {
		return fmt.Errorf("resolve %s: %w", path, err)
	}
	if b.seen[abs] {
		return nil
	}
	b.seen[abs] = true

	f, err := os.Open(abs)
	if err != nil {
		return fmt.Errorf("open %s: %w", abs, err)
	}
	defer f.Close()

	dir := filepath.Dir(abs)
	b.out.WriteString(fmt.Sprintf("// ─── bundled: %s ───\n", filepath.Base(abs)))

	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := scanner.Text()
		trimmed := strings.TrimSpace(line)

		if strings.HasPrefix(trimmed, "// @import ") {
			imp := strings.TrimSpace(strings.TrimPrefix(trimmed, "// @import "))
			if err := b.bundle(filepath.Join(dir, imp)); err != nil {
				b.out.WriteString(fmt.Sprintf("// [bundler] WARNING: %s: %v\n", imp, err))
			}
			continue
		}
		// suppress duplicate @layer from imports
		if strings.HasPrefix(trimmed, "// @layer ") && b.out.Len() > 120 {
			continue
		}
		b.out.WriteString(line)
		b.out.WriteByte('\n')
	}
	return scanner.Err()
}

func main() {
	outFlag := flag.String("o", "", "output file (default: stdout)")
	flag.Parse()

	if flag.NArg() < 1 {
		fmt.Fprintln(os.Stderr, "usage: phantom-bundler <input.js> [-o output.js]")
		os.Exit(1)
	}

	b := &bundler{seen: make(map[string]bool)}
	b.out.WriteString("// phantom bundle — generated by phantom-bundler\n")
	b.out.WriteString(fmt.Sprintf("// entry: %s\n\n", flag.Arg(0)))

	if err := b.bundle(flag.Arg(0)); err != nil {
		fmt.Fprintf(os.Stderr, "error: %v\n", err)
		os.Exit(1)
	}

	result := b.out.String()
	if *outFlag == "" || *outFlag == "-" {
		fmt.Print(result)
	} else {
		if err := os.WriteFile(*outFlag, []byte(result), 0644); err != nil {
			fmt.Fprintf(os.Stderr, "write %s: %v\n", *outFlag, err)
			os.Exit(1)
		}
		fmt.Printf("bundled → %s (%d bytes)\n", *outFlag, len(result))
	}
}
