// mirrors: I rank Arch Linux ARM mirrors by latency and rewrite
// pacman.conf with the fastest ones at the top.
// Run this at setup and again whenever downloads feel slow.
// Basically reflector but lighter and baked into phantom.
package main

import (
	"fmt"
	"net/http"
	"os"
	"sort"
	"strings"
	"time"
)

const PACMAN_CONF = "/data/phantom/rootfs/etc/pacman.conf"

// I got this list from the official Arch ARM mirrorlist
var mirrors = []string{
	"https://mirror.archlinuxarm.org",
	"https://mirrors.edge.kernel.org/archlinuxarm",
	"https://de3.mirror.archlinuxarm.org",
	"https://sg.mirror.archlinuxarm.org",
	"https://au.mirror.archlinuxarm.org",
	"https://mirrors.dotsrc.org/archlinuxarm",
	"https://mirror.archlinuxarm.org",
	"https://archlinuxarm.org",
}

type result struct {
	url     string
	latency time.Duration
	ok      bool
}

func probe(url string, ch chan<- result) {
	start := time.Now()
	resp, err := http.Head(url + "/aarch64/core/os/aarch64/")
	ok := err == nil && resp.StatusCode < 400
	ch <- result{url: url, latency: time.Since(start), ok: ok}
}

func main() {
	fmt.Printf("probing %d mirrors...\n", len(mirrors))

	ch := make(chan result, len(mirrors))
	for _, m := range mirrors {
		go probe(m, ch)
	}

	results := make([]result, 0, len(mirrors))
	for range mirrors {
		r := <-ch
		if r.ok {
			results = append(results, r)
			fmt.Printf("  %-55s %dms\n", r.url, r.latency.Milliseconds())
		} else {
			fmt.Printf("  %-55s unreachable\n", r.url)
		}
	}

	sort.Slice(results, func(i, j int) bool {
		return results[i].latency < results[j].latency
	})

	if len(results) == 0 {
		fmt.Fprintln(os.Stderr, "no reachable mirrors")
		os.Exit(1)
	}

	fmt.Printf("\nfastest: %s (%dms)\n", results[0].url, results[0].latency.Milliseconds())

	// rewrite pacman.conf with top 3 mirrors
	top := 3
	if len(results) < top {
		top = len(results)
	}

	var sb strings.Builder
	sb.WriteString("# Generated by phantom-mirrors — do not edit manually\n")
	sb.WriteString("[options]\n")
	sb.WriteString("HoldPkg          = pacman glibc\n")
	sb.WriteString("Architecture     = aarch64\n")
	sb.WriteString("CheckSpace\n")
	sb.WriteString("ParallelDownloads = 5\n\n")

	for _, repo := range []string{"core", "extra", "community", "alarm", "aur"} {
		sb.WriteString(fmt.Sprintf("[%s]\n", repo))
		for _, r := range results[:top] {
			sb.WriteString(fmt.Sprintf("Server = %s/$arch/%s/os/$arch\n", r.url, repo))
		}
		sb.WriteString("\n")
	}

	if err := os.WriteFile(PACMAN_CONF, []byte(sb.String()), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "failed to write pacman.conf: %v\n", err)
		os.Exit(1)
	}
	fmt.Printf("wrote %s with top %d mirrors\n", PACMAN_CONF, top)
}
